name: Upload Artifacts
description: Upload Crate Examples as Artifacts
inputs:
  name:
    description: Name of the artifact
    required: true
  target:
    description: Cargo build target
    required: true
  file_regex:
    description: Regular expression to match artifact files in the build directory
    required: true
  artifacts:
    description: Temporary artifacts path
    required: true
    default: 'target/artifacts'
  compress:
    description: Specify 'zip' or 'tgz' to compress artifacts into single file
runs:
  using: composite
  steps:
      - shell: bash
        run: |
          mkdir -p ${{ inputs.artifacts }}
          OUTDIR=$(realpath ${{ inputs.artifacts }})

          echo "Collect built artifacts"
          pushd target/${{ inputs.target }}/release
          find . -type f -regextype posix-extended -regex '${{ inputs.file_regex }}' -exec cp {} ${OUTDIR}/. \;
          popd

          echo "Collect LICENSE if available"
          if [ -e LICENSE ]; then
            cp LICENSE $OUTDIR/.
          fi

          echo "ARTIFACT_PATH='${{ inputs.artifacts }}/*'" >> $GITHUB_ENV 
        
      - shell: bash
        if: ${{ inputs.compress == 'zip' }}
        run: |
          pushd ${{ inputs.artifacts }}
          zip -r ${{ inputs.name }}.zip ./*
          popd
          echo "ARTIFACT_PATH='${{ inputs.artifacts }}/${{ inputs.name }}.zip'" >> $GITHUB_ENV 
        
      - shell: bash
        if: ${{ inputs.compress == 'tgz' }}
        run: |
          pushd ${{ inputs.artifacts }}
          tar -czvf ${{ inputs.name }}.tgz ./*
          popd
          echo "ARTIFACT_PATH='${{ inputs.artifacts }}/${{ inputs.name }}.tgz'" >> $GITHUB_ENV 
        
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}
          path: ${{ env.ARTIFACT_PATH }}
