name: Upload Artifacts
description: Compress files and upload as an artifact
inputs:
  name:
    description: Name of the output artifact
    required: true
  files:
    description: Glob patterns of files, relative to base_dir
    required: true
  files_cwd:
    description: Glob patterns of files, relative to cwd 
    required: true
  base_dir:
    description: Base directory, whose structure will be stripped from the files list
    default: '.'
  out_dir:
    description: Temporary output directory for artifacts
    default: 'target/artifacts'
  compress:
    description: Specify 'zip' or 'tgz' to compress artifacts into single file
    default: ''
runs:
  using: composite
  steps:
      - shell: bash
        run: |
          # Enable globstar
          shopt -s globstar

          # Prepare output path
          mkdir -p ${{ inputs.out_dir }}
          OUTDIR=$(realpath ${{ inputs.out_dir }})

          echo "Collect built artifact into $OUTDIR"

          pushd ${{ inputs.base_dir }}
          FILE_LIST="${{ inputs.files }}"
          for file in $FILE_LIST; do
            cp --parents $file $OUTDIR/.
          done
          popd

          FILE_LIST="${{ inputs.files_cwd }}"
          for file in $FILE_LIST; do
            cp --parents $file $OUTDIR/.
          done
 
          echo "ARTIFACT_PATH=${{ inputs.out_dir }}/*" >> $GITHUB_ENV 
        
      - name: Archive zip
        shell: bash
        if: ${{ inputs.compress == 'zip' }}
        run: |
          pushd ${{ inputs.out_dir }}
          zip -r ${{ inputs.name }}.zip ./*
          popd
          echo "ARTIFACT_PATH=${{ inputs.out_dir }}/${{ inputs.name }}.zip" >> $GITHUB_ENV 
        
      - name: Archive tgz
        shell: bash
        if: ${{ inputs.compress == 'tgz' }}
        run: |
          pushd ${{ inputs.out_dir }}
          tar -czvf ${{ inputs.name }}.tgz ./*
          popd
          echo "ARTIFACT_PATH=${{ inputs.out_dir }}/${{ inputs.name }}.tgz" >> $GITHUB_ENV 
        
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}
          path: ${{ env.ARTIFACT_PATH }}
