name: Parses github.ref
description: Parses the input string and determines if its a semver
outputs:
  ref_type:
    value: ${{ steps.parse.outputs.ref_type }}
    description: |-
      Parses the ref and provides a type string

      "refs/pull/12/merge"     -> "pr"
      "refs/heads/main"        -> "branch"
      "refs/tags/hello"        -> "tag"
      "refs/tags/v0.1.0"       -> "tag-semver-release"
      "refs/tags/v0.1.0-pre.1" -> "tag-semver-pre-release"
runs:
  using: composite
  steps:
      - name: Parse
        id: parse
        shell: bash
        run: echo "ref_type=$(python ${{ github.action_path }}/parse_ref.py ${{ github.ref }})" >> $GITHUB_OUTPUT