name: Cargo xwin
description: Build with cargo xwin
inputs:
  command:
    description: Command
    required: false
    default: build
  profile:
    description: Build profile
    required: false
    default: release
  target:
    description: Build target architecture
    required: false
    default: x86_64-pc-windows-msvc
runs:
  using: composite
  steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ inputs.target }}
      - shell: bash
        run: cargo install cargo-xwin
      - shell: bash
        run: cargo xwin cache xwin
      - shell: bash
        run: cargo xwin ${{ inputs.command }} --${{ inputs.profile }} --target ${{ inputs.target }}