name: Cargo xwin
description: Build with cargo xwin
inputs:
  targets-ext:
    description: Additional targets
runs:
  using: composite
  steps:
      - run: cargo install cargo-xwin
        shell: bash
      - run: cargo xwin cache xwin
        shell: bash
      - run: cargo xwin build --release ${{ inputs.targets-ext }} --target x86_64-pc-windows-msvc
        shell: bash