name: Cross-Platform Build and Release Artifacts

env:
  PACKAGE_NAME: 'ser-file'
  ARTIFACTS_NIX: './examples/ser'
  ARTIFACTS_WIN: './examples/(ser.exe|ser.pdb)'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9A-Za-z]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  check-prerelease:
    runs-on: ubuntu-latest
    outputs:
      is_prerelease: ${{ steps.check.outputs.is_prerelease }}
    steps:
      - id: check
        run: |
          if [[ "${{ github.ref_name }}" == *-* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

  build-nix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
          - target: aarch64-unknown-linux-gnu
          - target: x86_64-apple-darwin
          - target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v5
      - uses: zijiren233/cargo-cross@v1
        with:
          command: build --all-targets
          profile: release
          targets: ${{ matrix.target }}
      - uses: ./.github/actions/artifacts/
        with:
          name: ${{ env.PACKAGE_NAME }}-${{ github.ref_name }}-${{ matrix.target }}
          target: ${{ matrix.target }}
          file_regex: ${{ env.ARTIFACTS_NIX }}
          compress: tgz

  build-win:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/xwin/
        with:
          command: build --all-targets
          profile: release
      - uses: ./.github/actions/artifacts/
        with:
          name: ${{ env.PACKAGE_NAME }}-${{ github.ref_name }}-x86_64-pc-windows-msvc
          target: x86_64-pc-windows-msvc
          file_regex: ${{ env.ARTIFACTS_WIN }}
          compress: zip

  release:
    needs:
      - check-prerelease
      - build-nix
      - build-win

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v4
        with:
          path: release_artifacts/
      - uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ needs.check-prerelease.outputs.is_prerelease == 'true' }}
          files: release_artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}