name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  parse_ref:
    name: Parse ref

    outputs:
      ref_type: ${{ steps.parse.outputs.ref_type }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - id: parse
        uses: ./.github/actions/ref_type/

  test:
    name: Test Suite
    
    strategy:
      matrix:
        target:
          - '--all-targets'
          - '--all-features --all-targets'
          - '--doc'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test ${{ matrix.target }}

  build:
    name: Build Artifacts

    needs:
      - parse_ref
      - test

    if: |-
      ${{
        needs.parse_ref.outputs.ref_type == 'tag-semver-release' ||
        needs.parse_ref.outputs.ref_type == 'tag-semver-pre-release'
      }}

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            convention: nix
          - target: aarch64-unknown-linux-gnu
            convention: nix
          - target: x86_64-apple-darwin
            convention: nix
          - target: aarch64-apple-darwin
            convention: nix
          - target: x86_64-pc-windows-msvc
            convention: win

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build Nix
        if: ${{ matrix.convention == 'nix' }}
        uses: zijiren233/cargo-cross@v1
        with:
          command: build --all-targets --all-features
          targets: ${{ matrix.target }}

      - name: Build Win
        if: ${{ matrix.convention == 'win' }}
        uses: ./.github/actions/xwin/
        with:
          command: build --all-targets --all-features
          target: ${{ matrix.target }}
      
      - name: Read artifact config
        id: artifacts
        run: jq -r 'to_entries[] | "\(.key)=\(.value | if type == "array" then join(" ") else . end)"' artifacts.json >> $GITHUB_OUTPUT

      - name: Upload Artifacts
        uses: ./.github/actions/artifacts/
        with:
          name: ${{ steps.artifacts.outputs.dist_name }}-${{ github.ref_name }}-${{ matrix.target }}
          base_dir: target/${{ matrix.target }}/release
          files: ${{ case( matrix.convention == 'win', steps.artifacts.outputs.artifacts_win, steps.artifacts.outputs.artifacts_nix ) }}
          files_cwd: ${{ steps.artifacts.outputs.artifacts_common }}
          compress: ${{ case( matrix.convention == 'win', 'zip', 'tgz' )}}

  release:
    needs:
      - parse_ref
      - build
    
    if: ${{ needs.parse_ref.outputs.ref_type == 'tag-semver-release' }}

    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v4
        with:
          path: dist/
      - uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ needs.check-prerelease.outputs.is_prerelease == 'true' }}
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs:
      - parse_ref
      - build

    env:
      PUBLISH_ARGS: |-
        ${{ case(
          needs.parse_ref.outputs.ref_type == 'tag-semver-release', '',
          '--dry-run'
        ) }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo publish $PUBLISH_ARGS
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
